#cloud-config

bootcmd:
    - useradd -m -c "Deployment user" deployuser

# Adding a user automatically disables default ubuntu user
users:
  - name: deployuser
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDN+JBPWHbViSin0QhZwllakXSTjE+6memHlokEL4hKbIQIyETKv//iZVUCE1lDnc0uE73cDKS8HVHR4S3N2WWHzeuStWIDnirOHE4SW3GgeQfu1H1DikHf7E+PT8qJhQWtAYzEJyFf4vgPn/KuNhJFRWXmR3zK3gACZWP1ON9fymoBzi5MG9YM44JJnGoYM3CX7Aav/1DwIR5Sc1jRJ6uxJTsH1qv7EC81hjmvMAT+DscD5yx5yU28VJ3LM0p2RrRDaZcjXGYviXUoXufZl9MbKrsya9nRrL4wiUgECrgbkYy3XJNN4LYZT9oeRqqzyU3H9N33of7KhcR78fPbt6dxq56f+gSNHOsImTLPsbfKMoRg01j1Pi3ambAdBaA9XLKfCn4rCNXVmjJ8CGuYCf2SW8ur9DG/v43PVeZerhdQJ6Jgg6nilJoqUBA38B6cFFuyNkK1DH8wRq2b55khEEKCRUA3jcvz44N7VD4SJfWr9vDz0xlpUgKTMijDg3/5RHmS6yGfE9fw0CHucRMF1z6gYjyyjpPkDcceobnS+370efsF/qfKXao4bfkHm+vUSfZlz5KfuLjggYjZzmKTTM50oJyrHgcOpxUvqJH2OWKiTHX8bVdlh/amzrALqr1zCg0amMulKmU4K4ucGUwWUF/m6aMgwA42HtAHSEc35oF3GQ== oss@cmills-Kudu-Pro

# install Ansible repository source
apt_sources:
  - source: "ppa:ansible/ansible"

apt_upgrade: true

# Installing packages will set apt_update to true
packages:
  - python
  - python-pip
  - software-properties-common
  - ansible

write_files:
  - content: |
      #!/bin/bash

      DIGITALOCEAN=(Get Key From https://cloud.digitalocean.com/settings/api/tokens)
      SLACK=(Get Key From https://my.slack.com/services/new/bot) 

      rm do.txt
  
      curl -sXGET "https://api.digitalocean.com/v2/droplets" \
       -H "Authorization: Bearer $DIGITALOCEAN" \
       -H "Content-Type: application/json" |\
       python -c 'import sys,json;data=json.loads(sys.stdin.read());\
                  print "ID\tName\tIP\tPrice\n";\
                  print "\n".join(["%s\t%s\t%s\t$%s"%(d["id"],d["name"],d["networks"]["v4"][0]["ip_address"],d["size"]["price_monthly"])\
                  for d in data["droplets"]])'| column -t > do.txt

      curl -F file=@do.txt -F initial_comment="Running Droplets" -F channels=#do -F token=$SLACK https://slack.com/api/files.upload
    path: /home/deployuser/send_daily_droplet_notices .sh
    owner: deployuser:deployuser
    permissions: '0755'
  - content: "0 09 * * * /home/deployuser/send_daily_droplet_notices.sh"
    owner: deployuser:deployuser
    path: /var/spool/cron/crontabs/deployuser
   
# Disable root login
disable_root: true
